# Generated by Django 5.1.7 on 2025-03-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto_persona',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
